baseURL = "https://lxyblog.dpdns.org/" # 确保这里使用你的最终域名
languageCode = "zh-cn"
title = "茉莉智元" # 你的博客名称
theme = "stack" # 主题名

[params]
  description = "记录个人学习、分享编程知识和生活思考的博客。" # 博客的简短描述，非常重要！


[author]
name = "茉莉智元"
homepage = "https://lxyblog.dpdns.org/"
[params.sidebar.avatar]
enabled = true
local = true
# 确保这里的路径和你放置的图片路径一致，假设放在 static/img/
src = "./stack/moli.png"